unique_ids:
  forms:
    Form1: XHWDORE2FVTMGBFUTLT7IFMNH4YVM7FH
    Form1.ItemTemplate1: '1684675983072457933956779.29614'
    Form1.ItemTemplate1.ItemTemplate2: '1684676442603765682523375.3726'
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: CJHR5HTB7ZF3XA5JA466AJ4GJE7W52AC
    theme.css: FWVS34VQLKJR2BY3PT4GVNP3ARCFGIIR
  scripts: {}
